name: db-m2_live_master-backup

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create DB backup file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.M2_LIVE_MYSQL_SSH_IP }}
          username: ${{ secrets.M2_LIVE_MYSQL_SSH_USER }}
          key: ${{ secrets.M2_LIVE_MYSQL_SSH_KEY }}
          script: |
            cd /home/deploy/sql-work/
            mysqldump -u${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} m2_live_master | gzip > m2_live_master_$(date +%Y%m%d%H%M)_bkp.sql.gz
            mv /home/deploy/sql-work/m2_live_master*.gz /media/data-center/sql-dump/m2-live-prod-001
